//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.ApplicationProject.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEgitim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEgitim()
        {
            this.TblEgitimSepet = new HashSet<TblEgitimSepet>();
            this.TblSatislar = new HashSet<TblSatislar>();
        }
    
        public int EgitimId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public int EgitimKategoriId { get; set; }
        public string Aciklama { get; set; }
        public string EgitimAdi { get; set; }
        public Nullable<decimal> EgitimFiyat { get; set; }
        public string EgitimResmi { get; set; }
        public string EgitimGunleri { get; set; }
        public string EgitimSaat { get; set; }
        public string CoachAdi { get; set; }
        public string CoachCinsi { get; set; }
        public string CoachDogumTarih { get; set; }
        public string CoachTel { get; set; }
        public string CoachEmail { get; set; }
    
        public virtual TblEgitimKategori TblEgitimKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEgitimSepet> TblEgitimSepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatislar> TblSatislar { get; set; }
        public virtual TblKullanici TblKullanici { get; set; }
    }
}
