//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.ApplicationProject.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEgitimKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEgitimKategori()
        {
            this.TblEgitim = new HashSet<TblEgitim>();
        }
    
        public int EgitimKategoriId { get; set; }
        public string EgitimKategoriAdi { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEgitim> TblEgitim { get; set; }
    }
}
